const { app, request, loginAs } = require('./helpers');
const { ROLES, PRODUCT_CATEGORIES } = require('../src/utils/constants');

// Regression: an empty name used to fail Joi validation with a message the
// desktop/web client swallowed, showing only "Validation failed" with no
// indication of which field was wrong.
test('empty required fields return a specific validation message', async () => {
  const { token } = await loginAs(ROLES.SUPERADMIN);

  const res = await request(app)
    .post('/api/products')
    .set('Authorization', `Bearer ${token}`)
    .send({ name: '', category: PRODUCT_CATEGORIES.STATIONERY, price: 10 });

  expect(res.status).toBe(400);
  expect(res.body.error).toBe('Validation failed');
  expect(res.body.details).toEqual(expect.arrayContaining([expect.stringContaining('name')]));
});

// Consolidated spec: SKU is generated by the system (STN-00001, ...) so the
// admin never types one; Product ID, SKU and barcode stay separate fields.
test('SKU is auto-generated per category and barcode stays a separate optional field', async () => {
  const { token } = await loginAs(ROLES.ADMIN);
  const create = (body) => request(app).post('/api/products').set('Authorization', `Bearer ${token}`).send(body);

  const first = await create({ name: 'Pen', category: PRODUCT_CATEGORIES.STATIONERY, price: 10, barcode: '8901234567890' });
  expect(first.status).toBe(201);
  expect(first.body.product.sku).toBe('STN-00001');
  expect(first.body.product.barcode).toBe('8901234567890');
  expect(first.body.product._id).not.toBe(first.body.product.sku);

  const second = await create({ name: 'Pencil', sku: '', category: PRODUCT_CATEGORIES.STATIONERY, price: 5 });
  expect(second.status).toBe(201);
  expect(second.body.product.sku).toBe('STN-00002');
  expect(second.body.product.barcode).toBeUndefined();

  const grocery = await create({ name: 'Rice', category: PRODUCT_CATEGORIES.GROCERY, price: 100 });
  expect(grocery.body.product.sku).toBe('GRO-00001');

  // Duplicate barcode is rejected; explicit SKUs are still accepted.
  const dupBarcode = await create({ name: 'Other', category: PRODUCT_CATEGORIES.STATIONERY, price: 1, barcode: '8901234567890' });
  expect(dupBarcode.status).toBe(409);
  const explicit = await create({ name: 'Legacy', sku: 'LEG-1', category: PRODUCT_CATEGORIES.STATIONERY, price: 1 });
  expect(explicit.body.product.sku).toBe('LEG-1');

  // Scanner lookup by barcode and partial search by SKU.
  const byBarcode = await request(app).get('/api/products?barcode=8901234567890').set('Authorization', `Bearer ${token}`);
  expect(byBarcode.body.products).toHaveLength(1);
  expect(byBarcode.body.products[0].name).toBe('Pen');
  const bySku = await request(app).get('/api/products?q=stn-0000').set('Authorization', `Bearer ${token}`);
  expect(bySku.body.products.map((p) => p.sku).sort()).toEqual(['STN-00001', 'STN-00002']);
});

test('product records and exposes who created it', async () => {
  const { token, user } = await loginAs(ROLES.ADMIN);

  const createRes = await request(app)
    .post('/api/products')
    .set('Authorization', `Bearer ${token}`)
    .send({ name: 'Marker', sku: `MARK-${Date.now()}`, category: PRODUCT_CATEGORIES.STATIONERY, price: 20, currentStock: 5 });
  expect(createRes.status).toBe(201);
  expect(createRes.body.product.createdBy).toMatchObject({ name: user.name, role: ROLES.ADMIN });

  const listRes = await request(app).get('/api/products').set('Authorization', `Bearer ${token}`);
  const found = listRes.body.products.find((p) => p._id === createRes.body.product._id);
  expect(found.createdBy).toMatchObject({ name: user.name, role: ROLES.ADMIN });

  // Public/anonymous storefront listing never leaks staff identity.
  const publicRes = await request(app).get('/api/products');
  const publicProduct = publicRes.body.products.find((p) => p._id === createRes.body.product._id);
  expect(publicProduct?.createdBy).toBeUndefined();
});

test('upload product image sets imageUrl', async () => {
  const { token } = await loginAs(ROLES.ADMIN);

  const createRes = await request(app)
    .post('/api/products')
    .set('Authorization', `Bearer ${token}`)
    .send({ name: 'Pen', sku: `PEN-${Date.now()}`, category: PRODUCT_CATEGORIES.STATIONERY, price: 10 });
  expect(createRes.status).toBe(201);
  const id = createRes.body.product._id;

  const png = Buffer.from('89504e470d0a1a0a0000000d49484452', 'hex');
  const imgRes = await request(app)
    .post(`/api/products/${id}/image`)
    .set('Authorization', `Bearer ${token}`)
    .attach('image', png, { filename: 'pen.png', contentType: 'image/png' });

  expect(imgRes.status).toBe(200);
  expect(imgRes.body.product.imageUrl).toMatch(/^\/uploads\/.+\.png$/);

  const getRes = await request(app).get(`/api/products/${id}`);
  expect(getRes.body.product.imageUrl).toBe(imgRes.body.product.imageUrl);
});

test('rejects non-image files and requires admin role', async () => {
  const { token } = await loginAs(ROLES.ADMIN);
  const { token: staffToken } = await loginAs(ROLES.STAFF);

  const createRes = await request(app)
    .post('/api/products')
    .set('Authorization', `Bearer ${token}`)
    .send({ name: 'Pencil', sku: `PENCIL-${Date.now()}`, category: PRODUCT_CATEGORIES.STATIONERY, price: 5 });
  const id = createRes.body.product._id;

  const staffRes = await request(app)
    .post(`/api/products/${id}/image`)
    .set('Authorization', `Bearer ${staffToken}`)
    .attach('image', Buffer.from('fake'), { filename: 'x.png', contentType: 'image/png' });
  expect(staffRes.status).toBe(403);

  const badTypeRes = await request(app)
    .post(`/api/products/${id}/image`)
    .set('Authorization', `Bearer ${token}`)
    .attach('image', Buffer.from('fake pdf'), { filename: 'x.txt', contentType: 'text/plain' });
  expect(badTypeRes.status).toBeGreaterThanOrEqual(400);
});
