const Product = require('../models/Product');
const InventoryLog = require('../models/InventoryLog');
const AppError = require('../utils/AppError');
const asyncHandler = require('../utils/asyncHandler');
const { applyStockChange } = require('../services/inventoryService');
const { INVENTORY_LOG_TYPES } = require('../utils/constants');
const { logAction } = require('../services/auditService');
const { getCategoryOrThrow } = require('../services/categoryService');
const { storeProductImage } = require('../services/productImageService');
const { generateSku } = require('../services/skuService');

function escapeRegex(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Normalises the three identifiers on create/update payloads:
//  - sku: blank → removed (so the controller auto-generates it)
//  - barcode: blank → unset (sparse unique index must not see '')
function normaliseIdentifiers(payload) {
  const out = { ...payload };
  if (out.sku !== undefined && (out.sku === null || String(out.sku).trim() === '')) delete out.sku;
  if (out.barcode !== undefined && (out.barcode === null || String(out.barcode).trim() === '')) {
    delete out.barcode;
    out.$unset = { ...(out.$unset || {}), barcode: 1 };
  }
  return out;
}

const listProducts = asyncHandler(async (req, res) => {
  const { category, q, barcode, sku, isAvailableOnline, isActive, lowStockOnly, sellableOnly, page, limit } = req.query;
  const filter = {};

  if (category) filter.category = category;
  if (isAvailableOnline !== undefined) filter.isAvailableOnline = isAvailableOnline;
  filter.isActive = isActive !== undefined ? isActive : true;
  // Free-text search matches name, SKU and barcode (partial, case-insensitive)
  // so a cashier can type either the product name or part of its code.
  if (q) {
    const re = new RegExp(escapeRegex(q), 'i');
    filter.$or = [{ name: re }, { sku: re }, { barcode: re }, { description: re }];
  }
  if (barcode) filter.barcode = barcode;
  if (sku) filter.sku = sku.toUpperCase();
  // Spec §4.1: out-of-stock products are hidden from sellable lists but kept.
  // Unauthenticated (storefront) callers always get sellable-only results.
  if (sellableOnly || !req.user) Object.assign(filter, Product.sellableFilter(), { isActive: filter.isActive });

  let query = Product.find(filter).sort({ name: 1 });
  if (lowStockOnly) {
    query = Product.find({ ...filter, isMadeToOrder: false, $expr: { $lte: ['$currentStock', '$reorderThreshold'] } });
  }
  // Staff/Admin/Super Admin (Inventory screen) can see who added each
  // product; the public storefront never gets staff identities, not even
  // the raw user id.
  query = req.user ? query.populate('createdBy', 'name role') : query.select('-createdBy');

  const total = await Product.countDocuments(query.getFilter());
  const products = await query.skip((page - 1) * limit).limit(limit);

  res.json({ products, total, page, limit });
});

const getProduct = asyncHandler(async (req, res) => {
  let query = Product.findById(req.params.id);
  query = req.user ? query.populate('createdBy', 'name role') : query.select('-createdBy');
  const product = await query;
  if (!product) throw new AppError(404, 'Product not found');
  res.json({ product });
});

const createProduct = asyncHandler(async (req, res) => {
  const category = await getCategoryOrThrow(req.body.category);
  const payload = normaliseIdentifiers({ ...req.body, createdBy: req.user._id });
  delete payload.$unset;
  if (payload.reorderThreshold === undefined) payload.reorderThreshold = category.defaultReorderThreshold;
  if (!payload.unit) payload.unit = category.unitType;
  // Consolidated spec: SKU is generated by the system so the admin never has
  // to invent one. Product ID (_id) and barcode stay separate fields.
  if (!payload.sku) payload.sku = await generateSku(payload.category);
  if (payload.barcode && (await Product.exists({ barcode: payload.barcode }))) {
    throw new AppError(409, `Barcode ${payload.barcode} is already assigned to another product`);
  }
  if (await Product.exists({ sku: payload.sku.toUpperCase() })) {
    throw new AppError(409, `SKU ${payload.sku} already exists`);
  }

  let product = await Product.create(payload);
  product = await product.populate('createdBy', 'name role');

  if (product.currentStock > 0) {
    await InventoryLog.create({
      product: product._id,
      productName: product.name,
      sku: product.sku,
      category: product.category,
      type: INVENTORY_LOG_TYPES.PURCHASE,
      previousStock: 0,
      quantityDelta: product.currentStock,
      resultingStock: product.currentStock,
      reason: 'Initial stock on product creation',
      actor: req.user._id,
      branch: product.branch,
    });
  }

  await logAction({ actorUser: req.user, action: 'product.create', entityType: 'Product', entityId: product._id, after: payload });
  res.status(201).json({ product });
});

const updateProduct = asyncHandler(async (req, res) => {
  if (req.body.category) await getCategoryOrThrow(req.body.category);
  const existing = await Product.findById(req.params.id);
  if (!existing) throw new AppError(404, 'Product not found');
  const before = Object.fromEntries(Object.keys(req.body).map((k) => [k, existing.get(k)]));

  const update = normaliseIdentifiers(req.body);
  if (update.barcode && (await Product.exists({ barcode: update.barcode, _id: { $ne: existing._id } }))) {
    throw new AppError(409, `Barcode ${update.barcode} is already assigned to another product`);
  }
  const product = await Product.findByIdAndUpdate(req.params.id, update, { new: true, runValidators: true }).populate(
    'createdBy',
    'name role'
  );
  await logAction({ actorUser: req.user, action: 'product.update', entityType: 'Product', entityId: product._id, before, after: req.body });
  res.json({ product });
});

// Spec §2 "Delete inventory / products" (admin, superadmin). Soft delete:
// the record stays for historical sales and reports (spec §4.1 rule 2).
const deleteProduct = asyncHandler(async (req, res) => {
  const product = await Product.findById(req.params.id);
  if (!product) throw new AppError(404, 'Product not found');
  if (!product.isActive) return res.json({ ok: true, product });

  product.isActive = false;
  await product.save();
  await logAction({
    actorUser: req.user,
    action: 'product.delete',
    entityType: 'Product',
    entityId: product._id,
    before: { isActive: true },
    after: { isActive: false },
  });
  res.json({ ok: true, product });
});

const adjustStock = asyncHandler(async (req, res) => {
  const { delta, reason } = req.body;
  const before = await Product.findById(req.params.id, 'currentStock');
  const { product, log } = await applyStockChange({
    productId: req.params.id,
    delta,
    type: INVENTORY_LOG_TYPES.ADJUSTMENT,
    reason,
    actor: req.user._id,
    actorRole: req.user.role,
    branch: req.user.branch,
  });

  await logAction({
    actorUser: req.user,
    action: 'inventory.adjust',
    entityType: 'Product',
    entityId: product._id,
    before: { currentStock: before ? before.currentStock : undefined },
    after: { currentStock: product.currentStock },
    details: { delta, reason },
  });
  res.json({ product, log });
});

const getProductInventoryLog = asyncHandler(async (req, res) => {
  const logs = await InventoryLog.find({ product: req.params.id }).sort({ createdAt: -1 }).limit(200);
  res.json({ logs });
});

// Spec: product photo, shown to staff in Inventory and to customers browsing
// the storefront catalog. Uploaded as a separate step after create/update so
// the form works the same whether or not a photo is attached.
const uploadProductImage = asyncHandler(async (req, res) => {
  if (!req.file) throw new AppError(400, 'No image file uploaded');
  const product = await Product.findById(req.params.id);
  if (!product) throw new AppError(404, 'Product not found');

  const before = { imageUrl: product.imageUrl };
  product.imageUrl = await storeProductImage(req.file);
  await product.save();
  await product.populate('createdBy', 'name role');

  await logAction({
    actorUser: req.user,
    action: 'product.image',
    entityType: 'Product',
    entityId: product._id,
    before,
    after: { imageUrl: product.imageUrl },
  });
  res.json({ product });
});

module.exports = {
  listProducts,
  getProduct,
  createProduct,
  updateProduct,
  deleteProduct,
  adjustStock,
  getProductInventoryLog,
  uploadProductImage,
};
