const Joi = require('joi');
// Category keys are validated against the categories collection in the
// controller (spec §4: categories are data, not a hard-coded enum).
const categoryKey = Joi.string().pattern(/^[a-z][a-z0-9_]*$/).max(40);

const createProductSchema = Joi.object({
  name: Joi.string().min(1).max(150).required(),
  // Omitted/blank → auto-generated by skuService (e.g. STN-00001). An explicit
  // value is still accepted for imports/legacy codes.
  sku: Joi.string().trim().max(50).allow('', null),
  barcode: Joi.string().trim().max(64).allow('', null),
  category: categoryKey.required(),
  unit: Joi.string().max(20), // omitted → category unitType
  price: Joi.number().min(0).required(),
  costPrice: Joi.number().min(0).default(0),
  currentStock: Joi.number().min(0).default(0),
  // Omitted → falls back to the category's defaultReorderThreshold.
  reorderThreshold: Joi.number().min(0),
  isMadeToOrder: Joi.boolean().default(false),
  isAvailableOnline: Joi.boolean().default(true),
  imageUrl: Joi.string().uri().allow('', null),
  description: Joi.string().max(2000).allow('', null),
  branch: Joi.string().max(100).allow('', null),
});

const updateProductSchema = Joi.object({
  name: Joi.string().min(1).max(150),
  barcode: Joi.string().trim().max(64).allow('', null),
  category: categoryKey,
  unit: Joi.string().max(20),
  price: Joi.number().min(0),
  costPrice: Joi.number().min(0),
  reorderThreshold: Joi.number().min(0),
  isMadeToOrder: Joi.boolean(),
  isAvailableOnline: Joi.boolean(),
  isActive: Joi.boolean(),
  imageUrl: Joi.string().uri().allow('', null),
  description: Joi.string().max(2000).allow('', null),
  branch: Joi.string().max(100).allow('', null),
}).min(1);

const adjustStockSchema = Joi.object({
  delta: Joi.number().invalid(0).required(),
  reason: Joi.string().max(300).required(),
});

const listProductsQuerySchema = Joi.object({
  category: categoryKey,
  // true → hide out-of-stock (spec §4.1); used by POS quick-sell + storefront.
  sellableOnly: Joi.boolean(),
  q: Joi.string().max(100),
  // Exact lookups for scanner / SKU input.
  barcode: Joi.string().max(64),
  sku: Joi.string().max(50),
  isAvailableOnline: Joi.boolean(),
  isActive: Joi.boolean(),
  lowStockOnly: Joi.boolean(),
  page: Joi.number().integer().min(1).default(1),
  limit: Joi.number().integer().min(1).max(200).default(50),
});

module.exports = {
  createProductSchema,
  updateProductSchema,
  adjustStockSchema,
  listProductsQuerySchema,
};
